# Experiment 11- Depth First Search

### AIM- Write a program in Python to Solve 8 queens problem using depth first search

In [1]:
import numpy as np
import pandas as pd

class NQueensSolver:
    def __init__(self):
        pass
        
    def set_queen(self, i, j, chessboard):
        new_chessboard = chessboard.copy()
        new_chessboard[i, j] = 1
        return new_chessboard
        
    def remove_queen(self, i, j, chessboard):
        new_chessboard = chessboard.copy()
        new_chessboard[i, j] = 0
        return new_chessboard
        
    def check_queen(self, i, j, n, chessboard):
        
        def in_boundary(row, col):
            return 0 <= row < n and 0 <= col < n
        
        # check row
        for col in range(n):
            if col != j and chessboard[i, col] == 1:
                return False

        # check column
        for row in range(n):
            if row != i and chessboard[row, j] == 1:
                return False

        # check diagonals
        diff = 0
        while in_boundary(i - diff, j - diff):
            if chessboard[i - diff, j - diff] == 1:
                return False
            diff += 1
            
        diff = 0
        while in_boundary(i - diff, j + diff):
            if chessboard[i - diff, j + diff] == 1:
                return False
            diff += 1
            
        diff = 0
        while in_boundary(i + diff, j - diff):
            if chessboard[i + diff, j - diff] == 1:
                return False
            diff += 1
            
        diff = 0
        while in_boundary(i + diff, j + diff):
            if chessboard[i + diff, j + diff] == 1:
                return False
            diff += 1

        return True
        
    def solve(self, n): # Depth Tree Search with Stack
        solutions = []
        root_data = {
            'row':-1,
            'chessboard': np.zeros((n, n), dtype=int)
        }
        
        stack = [root_data]
        while len(stack) > 0:
            data = stack.pop()
            
            row = data['row']
            chessboard = data['chessboard']
            
            if row == n - 1:
                solutions.append(chessboard)
            else:
                row += 1
                
                for col in range(n-1, -1, -1): # Iterate through n-1, n-2, ..., 3, 2, 1, 0
                    if self.check_queen(row, col, n, chessboard):
                        data = {
                            'row': row, 
                            'chessboard': self.set_queen(row, col, chessboard)
                        }
                        stack.append(data)
        
        return solutions

solver = NQueensSolver()
for soln in solver.solve(5):
    print(soln, '\n')

[[1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]] 

[[1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]] 

[[0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]] 

[[0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]] 

[[0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]] 

[[0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]] 

[[0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]] 

[[0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]] 

[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]] 

[[0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]] 

